### ISSUE TITLE
Need to cache sounds 

### ISSUE THREAD

**Issue by psi77** [eQualityTime/ovfplayer#89]
We cache boards and images but not sounds currently

**Comment by blaise17** [comment]
Possibly need something like this to play them from the cache once we have them cached: https://stackoverflow.com/questions/17762763/play-wav-sound-file-encoded-in-base64-with-javascript

**Comment by joereddington** [comment]
Here's a an obz file http://joereddington.com/test4.obz it has been tested as valid obz by https://www.openboardformat.org/tools, However it isn't accepted by Cough Drop - possibly because Cough Drop doesn't support sounds-by-url.  It was created by 

- building a 2 by 1 board in Cough Drop
- Adding a sound to each button 
- downloading and extracting the obz 
- editing the obf file (and json manifest) to take away the links from one button and the filepath from another (Coughdrop obz files give both a file for local devices and a link to a watched version. 
- deleting the local copy of one file
- zipping the folder again (terminal, not macOS default) and renaming.)

**Comment by blaise17** [comment]
For using the above file it is also necessary to remove the reference to the url only sound from the manifest as otherwise it claims there's a file for it which doens't exist.
